### ISSUE TITLE
February Meeting

### ISSUE THREAD

**Issue by noise** [llimllib/computer#15]
Happy new year!

Looks like we missed January due to holidays/babies/flu/etc, but let's try for Feb - Tues or Weds the 3rd or 4th. Please weigh in if you have any strong preference else we'll likely go for Tues.

@kencochrane @johncosta @rektide @xach @tlots @mtdonahue @statik @rlandry @justinsteele @mdesjardins @mpistrang @adorsk @llimllib @jsmecham @neruson @sogrady @coreygilmore

**Comment by llimllib** [comment]
Either works for me. Let's do it!

**Comment by xach** [comment]
Tuesday's a bit better for me.

**Comment by neruson** [comment]
Sounds great! I can do Tuesday, not Wednesday.

**Comment by sogrady** [comment]
Back to my usual schedule of missing this, as I'll be in Europe. Someone
pour one out for me.

**Comment by noise** [comment]
Ok, a couple of votes for Tuesday seals the deal. Tues Feb 3rd it is, 7pm, or earlier if you are starving.

**Comment by llimllib** [comment]
Sounds good, site updated and pushed
