### ISSUE TITLE
Add "slackin" widget on our page to promote more usage of slack channel

### ISSUE THREAD

**Issue by noise** [llimllib/computer#16]
see: http://rauchg.com/slackin/

**Comment by llimllib** [comment]
Test it: https://portland-ca-slackin.herokuapp.com/

**Comment by llimllib** [comment]
Seems that the API call has been killed dead by @slackhq :( :no_bell: :no_bicycles: :no_entry: :no_entry_sign: :no_good:

https://twitter.com/levelsio/status/565604963813163010
