### ISSUE TITLE
March meeting

### ISSUE THREAD

**Issue by llimllib** [llimllib/computer#17]
How is March 3 for people?

Also, suggestions for different venues to mix it up?

**Comment by sogrady** [comment]
As for venue, has anybody been to King's Head? Decent beer list, good
candidate for having room to gather.

**Comment by noise** [comment]
Mar 3 works for me and +1 for Kings head as an option, nice space.

**Comment by llimllib** [comment]
Do we want to try KH for next meetup? Agree that it'd be a good option, it's quiet and has plenty of parking.

**Comment by suidroot** [comment]
Both KH and Mar 3 work for me

**Comment by jsmecham** [comment]
March 3rd works for me. Kings Head sounds great. Been wanting to try it.
